# Generated by Django 5.1 on 2024-08-20 07:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='photo'),
        ),
    ]
