# Generated by Django 5.1 on 2024-08-19 08:29

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_id_alter_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_photo_1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_photo_2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_photo_3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_photo_4',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('AA', 'Addis Ababa'), ('AR', 'Afar Region'), ('AM', 'Amhara Region'), ('BG', 'Benishangul-Gumuz Region'), ('DD', 'Dire Dawa'), ('GR', 'Gambela Region'), ('HR', 'Harari Region'), ('OR', 'Oromia Region'), ('SR', 'Sidama Region'), ('SM', 'Somali Region'), ('SN', 'Southern Nations'), ('TR', 'Tigray Region')], max_length=100),
        ),
    ]
